### ISSUE TITLE
MoTrPAC logo does not show up on the MoTrPAC page

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/DRC-Portal-Issues#65]
<img width="1187" alt="Screenshot 2024-09-12 at 11 56 40 PM" src="https://github.com/user-attachments/assets/ee2b868b-a73c-46a2-adc5-64f985d1c771">

**Comment by jeevangelista** [comment]
fixed

**Comment by heesukim628** [comment]
@jeevangelista  still facing the same issue
<img width="962" alt="image" src="https://github.com/user-attachments/assets/d1d54115-bc4c-4eaa-af87-9adabfe6945c">
https://data.cfde.cloud/processed/gene_set/ffef97be-3741-54b3-8eb5-711972a9421e

<img width="1110" alt="image" src="https://github.com/user-attachments/assets/59da9169-f4aa-407f-b833-97121f34641b">

**Comment by jeevangelista** [comment]
it's working now. Idk what happened
